/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Table;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
        System.out.println("hello1");
    }

    public Edit(int noData) throws IOException {
        initComponents();
        System.out.println("hello2");

//        UserXX.setText(msg);
//
//        String user = UserXX.getText();
        FileReader fileInput;
        BufferedReader bufferedInput;

        try {
            fileInput = new FileReader("database.txt");
            bufferedInput = new BufferedReader(fileInput);
        } catch (Exception e) {
            System.err.println("Database tidak ditemukan");
            System.err.println("Silahkan tambahkan data terlebih dahulu");
            File file = new File("src/database.txt");
//            TambahKegiatan(user);
            return;
        }

        String judulKegiatan = "", tanggalInput = "", due = "", jenisKegiatan = "", prioritasKegiatan = "", sisaWaktu = "", progress = "", people = "";
        int nomor = 0;
        String data = bufferedInput.readLine();
        while (data != null) {
            nomor++;
            if (nomor == noData) {
                StringTokenizer stringToken = new StringTokenizer(data, "_");
                judulKegiatan = stringToken.nextToken();
                tanggalInput = stringToken.nextToken();
                due = stringToken.nextToken();
                jenisKegiatan = stringToken.nextToken();
                prioritasKegiatan = stringToken.nextToken();
                sisaWaktu = stringToken.nextToken();
                progress = stringToken.nextToken();
                people = stringToken.nextToken();

                Nama.setText(judulKegiatan);
                Tanggal.setText(tanggalInput);
                Due.getDate();
                Jenis.setText(jenisKegiatan);
                Prioritas.setText(prioritasKegiatan);
                AddPeople.setText(people);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        Due = new com.toedter.calendar.JDateChooser();
        Prioritas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Jam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AddPeople = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Jenis = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UserXX = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Prioritas");

        Prioritas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrioritasActionPerformed(evt);
            }
        });

        jLabel8.setText("Jam");

        jLabel4.setText("Tambah Orang");

        jLabel1.setText("Nama Kegiatan");

        jLabel2.setText("Tanggal Input ");

        Tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Kegiatan");

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel7.setText("Username : ");

        jLabel5.setText("Due Date");

        UserXX.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel1)
                        .addComponent(Prioritas)
                        .addComponent(Jenis)
                        .addComponent(Tanggal)
                        .addComponent(Nama)
                        .addComponent(jLabel4)
                        .addComponent(AddPeople)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(UserXX, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Due, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addComponent(Jam))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(633, Short.MAX_VALUE)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(UserXX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(63, 63, 63)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Due, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Jam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Prioritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(AddPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(97, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrioritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrioritasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrioritasActionPerformed

    private void TanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        Calendar cal = Calendar.getInstance();

        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");

        String User = UserXX.getText();
        String judulKegiatan = Nama.getText();
        String tanggal = Tanggal.getText();
        String due = String.valueOf(date.format(Due.getDate()));
        String jenisKegiatan = Jenis.getText();
        String prioritasKegiatan = Prioritas.getText();
        String sisaWaktu = "";
        String progress = "0%";
        String people = AddPeople.getText();

        try {

            SisaJam sisa = new SisaJam();

            Locale lokal = null;

            String jam = Jam.getText();

            ZoneId zone = ZoneId.systemDefault();
            LocalTime time = LocalTime.now(zone);
            //            String jam3 = Jam.getText();

            int tahun = cal.get(Calendar.YEAR);
            int bulan = cal.get(Calendar.MONTH) + 1;
            int tanggall = cal.get(Calendar.DAY_OF_MONTH);

            String tahun1 = Integer.toString(tahun);
            String bulan1 = Integer.toString(bulan);
            String tanggal1 = Integer.toString(tanggall);

            String tanggal2 = String.valueOf(date.format(Due.getDate()));

            String pola = "dd-MM-yyyy HH:mm:ss";
            String waktuSatuStr = (tanggal2 + " " + jam + ":00");
            String waktuDuaStr = (tanggal1 + "-" + bulan1 + "-" + tahun1 + " " + time);
            Date waktuSatu = SisaJam.konversiStringkeDate(waktuSatuStr, pola, lokal);
            Date WaktuDua = SisaJam.konversiStringkeDate(waktuDuaStr, pola, lokal);
            String hasilSelisih = SisaJam.selisihDateTime(waktuSatu, WaktuDua);
            sisaWaktu = hasilSelisih;
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Please Input Data Correctly");
        }

        //
        //        try {
        //            TambahKegiatan(judulKegiatan, tanggal, due, jenisKegiatan, prioritasKegiatan, sisaWaktu, progress, people);
        //            String data[] = {judulKegiatan, tanggal, due, jenisKegiatan, prioritasKegiatan, sisaWaktu, progress, people};
        //
        //            DefaultTableModel tblJadwal = (DefaultTableModel) Jadwal.getModel();
        //
        //            tblJadwal.addRow(data);
        //        } catch (IOException ex) {
        //            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        //        }
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddPeople;
    private com.toedter.calendar.JDateChooser Due;
    private javax.swing.JTextField Jam;
    private javax.swing.JTextField Jenis;
    private javax.swing.JTextField Nama;
    public javax.swing.JTextField Prioritas;
    private javax.swing.JButton Save;
    public javax.swing.JTextField Tanggal;
    private javax.swing.JTextField UserXX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    private void filter(String query) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
